### ISSUE TITLE
Round parenthesis ()

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#109]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-6|RM|14|354
***

### Issue Description
Round parenthesis () can be applied to more than one dataset.
 
### Proposed Solution
Change the value in the column "operand Datasets" fro 1 to 1…N

**Comment by capacma** [comment]
The round parenthesis () can be applied to 1 expression (and not to more than 1 - this would raise a syntax error).
From a formal point of view the round parenthesis is a syntactical element and not an operator. It should be taken out of the table at page 14 and 21. The text at the top of page 21 should include the sentence:
Parentheses can be used to override the operator precedence, e.g. "(A + B) * C".
