### ISSUE TITLE
It is reported: "The Variable name can be aliased …" but there is not "as" in the syntax.

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#143]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-41|RM|35|1035
***

### Issue Description
It is reported: "The Variable name can be aliased …" but there is not "as" in the syntax.

### Proposed Solution
Add the "as" in the sintax in the signature for a variable.

**Comment by capacma** [comment]
The as is already present in the syntax (RM line 999.
