### ISSUE TITLE
"Constant-string"

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#144]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV2-42|RM|35|1057
***

### Issue Description
There is no "constant-string" in the syntax.

### Proposed Solution
Maybe it should be added with the alias (see comment above).

**Comment by capacma** [comment]
The constant-string is already present (RM line 999)
