### ISSUE TITLE
No limitation for all types of components. (Membership operator)

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#150]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-43|RM|41|Membership operator
***

### Issue Description
Applicable to all components (not limited to measures and attributes as in the reference manual).

### Proposed Solution
Allow  Membership operator to be applied to all types of components.

**Comment by capacma** [comment]
Treated as issue #263.
