### ISSUE TITLE
Function body with  list of statements.

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#181]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-46|RM|57|User function
***

### Issue Description
Function body with  list of statements  return statement (alternative: define procedure).

**Comment by capacma** [comment]
I propose to close this issue (originally raised by me) because it is covered by  #287, i.e. by creating in the RM a **define procedure** statement.
