### ISSUE TITLE
Core language.

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#283]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-19|UM|54|Core language
MC-19|RM|14|Core language
***

### Issue Description
Complete the core language. Type system?

### Proposed Solution
Open

**Comment by capacma** [comment]
I assign it to Dragan for the type system

**Comment by dragan-ivanovic** [comment]
The description of the proposed module and type system is in the attached document.

**Comment by dragan-ivanovic** [comment]
[type-sys.pdf](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/754361/type-sys.pdf)

**Comment by dragan-ivanovic** [comment]
The updated specification of the type system, based on further discussion in Rome and teleconferences: 
[type-sys-update-2017-02-22.pdf](https://github.com/vtl-sdmx-task-force/sdmx-vtl/files/794337/type-sys-update-2017-02-22.pdf)

**Comment by capacma** [comment]
In the last meeting there was a proposal to have a time_period primitive data type, distinguished from the date/timestamp type.

**Comment by capacma** [comment]
There are no conversion functions to convert from one type to another (in the draft VTL 1.1 we only have from string_from_date).
As VTL is strongly typed, it seems reasonable to have a set of conversion functions (e.g. to_string, to_date, to_number, to_time_period etc.)
