### ISSUE TITLE
"major or equal than"

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#302]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ESTAΤ-18|RM|63|2252
***

### Issue Description
"major or equal than"

### Proposed Solution
"greater than or equal to"

**Comment by egreising** [comment]
The typo is in page 63, not 61 as originally posted (corrected).
The correct expression are "greater than", "greater than or equal to", "less than", "less than or equal to". (Cambridge dictionary, "Symbols and typographic conventions" - http://dictionary.cambridge.org/grammar/british-grammar/writing/punctuation)

**Comment by stratosn** [comment]
Duplicate of #303.
