### ISSUE TITLE
Boolean operators issues

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#40]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
DI-2|RM|85|Boolean operators and functions p. 85-89
DI-3|RM|85|Boolean operators and functions (all)
DI-5|RM|85|Boolean operators and functions (all)
DI-6|RM|85|Boolean operators and functions (in general, possibly in other sections) 
DI-7|RM|85|Boolean operators and functions (in general, possibly in other sections) 
***
*(excel ref: 110 to 114)*

The behaviour of the relational operators (=, <>, >, >=, etc.) on single-measure and multi-measure data sets is ambiguous. The two presented alternatives for creating the 'condition' and 'xyz_condition' components in the resulting dataset overlap because they are not mutually exclusive. The description is repeated and scattered in many places in the RefMan, which makes it difficult to keep consistent and maintain.
-> Unambiguously define the behaviour of the relational operators on single- and multi-measure datasets.
The behaviour of various Boolean operators on datasets that create 'condition' or 'xyz_condition' in the resulting dataset is not expressible using the core mechanisms: the join expressions and the scalar Boolean operators.
-> Express the behaviour of various Boolean operators applied to datasets using (and make sure it is consistent with) the core mechanisms: scalar relational operators and join expressions. 
Operators whose name starts with not are not consistently named and interpreted.  Some of them (such as not_exists_in) have an underscore after not, and some doan underscore. Therefore the syntax does not follow the same logic and may be difficult to unambiguously interpret.
-> Make the systematic use of not explicitly defined for all operators with the following syntactic forms:The form A not OP B (where OP is a binary operator other than is) is always interpreted as: not(A OP B).Example: A not exists_in B is interpreted by the parser as not (A exists_in B),The form A is not B is equivalent to:not(A is B),The form A not between C and D is equivalent to:
The description of dataset parameters usually starts with the dataset keyword followed by one or more groups enclosed in { .. .}* or {…}+.  However, these curly braces seem to be meta-syntax for repetition, while the mandatory opening and closing curly braces are omitted by mistake.
-> Correct the error.
In many cases the the description of parameters gives two cases: parameters are datasets (followed with a dataset and a structure specification), and the other worded as "are input Dataset or Boolean scalars." It is unclear what distinguishes a dataset (the first case) and an input dataset (the second case).
-> Clarify the meaning and put the correct wording.
@capacma
The current semantics of the Boolean operators is not correct (see comments below).
Possible solution:
1. Redefine the Boolean operators to produce only 1 Boolean measure in the resulting dataset. This solution avoids the incorrect behaviour explained in the comments. In particular, do not allow using the relational operators (>, >= etc.) on multi-measure datasets (i.e. always specify 1 component of the dataset). 
2. Distinguish the system-created Boolean measures (like "condition" created by the operator ">") from the user-created Boolean measures. They should be treated in different ways by filter, check etc. (or at least define precisely how check treats a dataset with multiple measures).
3. Evaluate an alternative solution to allow the Boolean values only in conditions (not in datasets). In this way the check operator would have as operands both a dataset and a condition to be verified.

**Comment by dragan-ivanovic** [comment]
One option for aligning the behavior of Boolean operators on data sets with join expressions is not to change the component names by appending "_component".

**Comment by bellomarini** [comment]
Independently of the name, the type and the number of the input measures (provided that the language constraints are satisfied), I suggest that the output measures are named CONDITION_1, CONDITION_2, ... , CONDITION_n. 

This would have the following pros:

* pre-define conventional Boolean code lists for the CONDITION variables;
* support for nested combinations without limited renaming.

**Comment by capacma** [comment]
The mechanism currently defined in VTL is not correct. Suppose we have 2 datasets:
dataset A has measures m1, m2
dataset B has measures m2, m3:
and we want to evaluate the following boolean expression (following the semantics described in the RM):
A > 0 and B > 0
A > 0 returns a dataset with measures m1_condition, m2_condition
B > 0 returns a dataset with measures m2_condition, m3_condition
A > 0 and B > 0 returns a dataset with the measure m2condition (the only measure common to both operands)
the result is not correct because the conditions on A.m1 and B.m3 **have been lost**.

**Comment by capacma** [comment]
1. The VTL Boolean values are true, false, null. The VTL operators (e.g. and, or etc.) use the 3 value logics described in the UM. However the RM does not specify how the operators filter and check manage the null value. The filter operator should interpret "null" as "false" (i.e. do not return the data point). A similar precision must done for the check operator.
2. The dataset operand of the check operator may contain several Boolean measures (in general and according to the semantics of >, >= etc.). The check operator returns a single boolean measure. The RM should specify how these measures are combined to produce the result. 
3. A dataset can have a Boolean measure not created by >, >= etc. The RM should describe how the boolean operators treat those boolean measures.

**Comment by bellomarini** [comment]
see issue #6

**Comment by stratosn** [comment]
Agreement provided in #6. Closed as duplicate.
