### ISSUE TITLE
Missing values treatment

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#45]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
MC-10|UM|8|Numeric operators
MC-10|RM|68|Numeric operators
***

### Issue Description
Make a decision to adopt either the description provided in "arithmetic operators" or in "mathematical_operators". Name of the chapter: numeric operators? 

How to treat the missing values: 

Solution 1: eliminate ++, + does not create zeros for the missing data (more efficient to implement on any platform), a distinct operator (e.g. sum (a,b,c) ) is used to create the zeros.

Solution 2: + creates the zeros,** and // : maybe not necessary

### Proposed Solution
Name: numeric, mathematical,  arithmetic (to be checked with @bellomarini and @dragan-ivanovic)

**Comment by bellomarini** [comment]
* For the name I would be in favor of _mathematical_.

* For the missing keys (i.e. keys appearing in just one of the two operands), I suggest that we do not create any zeros and do not have the ++, --, **, // versions (Solution 1). 
In other words, the absence of a data point in the data set should a missing value and not an implicit zero. Therefore, **zeros should be explicit**.

When it's not the case, the we should adopt specific operators to make the conversion, e.g. **listsum**.

**Comment by capacma** [comment]
Both UM page 7 and RM page 68 are coherent. They refer to numeric operators and functions (i.e. applied to numbers). Therefore there are no changes to be done.

**Comment by stratosn** [comment]
Agreement provided in #8. Closed as duplicate.
