### ISSUE TITLE
The keyword in the procedure is used with a different meaning than in as a “comparator”

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#66]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
ECB2-7|UM|53|1825
***

### Issue Description
The keyword in the procedure is used with a different meaning than in as a “comparator”

### Proposed Solution
in could be the default value in procedures and thus omitted

**Comment by vignola** [comment]
this is the same issue than #65
