### ISSUE TITLE
Join Expression & Functionalities.

### ISSUE THREAD

**Issue by stratosn** [vtl-sdmx-task-force/sdmx-vtl#70]
reporter issue reference|document (UM/RM/EBNF)|page|line
:--|:--|--:|--:
LV-11|UM|66|50
***

### Issue Description
The join expression is used also when there is no join and has a lot functionalities, the name is not so allined whith the potentiality of this operator.

### Proposed Solution
Find another name.

**Comment by capacma** [comment]
This issue is treated in #249.
